server:
    port: 8761
eureka:
    instance:
      hostname: localhost
    client:
      register-with-eureka: false
      fetch-registery: false
    server:
      response-cache-update-interval-ms: 5000
spring:
  application:
    name: eureka
