server:
  port: 8300
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    client:
      fetch-registry: false
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
spring:
  application:
    name: WalletService
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ecommerce?createDatabaseIfNotExist=true&amp;amp;useUnicode=true&amp;amp;characterEncoding=utf-8&amp;amp;autoReconnect=true
    username: root
    password: Aa123456
  jpa:
    show-sql: true
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    hibernate.ddl-auto: create-drop
  main:
    banner-mode: off

  mail:
    host: smtp.gmail.com
    port: 587
    username: pulsebs.softeng@gmail.com
    password: xssyjwawrmvrkgag
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com



